/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonColor, ButtonLayout, ButtonTypes } from "./components/elements/button/button.model";
export { ButtonColor, ButtonLayout, ButtonTypes } from "./components/elements/button/button.model";
export namespace Components {
    interface MyButton {
        "color": ButtonColor;
        "disabled": boolean;
        "href": string;
        "iconUrl": string;
        "isClear": boolean;
        "layout": ButtonLayout;
        "target": string;
        "type": ButtonTypes;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
export interface MyButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLMyButtonElement;
}
declare global {
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-button": HTMLMyButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyButton {
        "color"?: ButtonColor;
        "disabled"?: boolean;
        "href"?: string;
        "iconUrl"?: string;
        "isClear"?: boolean;
        "layout"?: ButtonLayout;
        "onTrpBtnReseted"?: (event: MyButtonCustomEvent<boolean>) => void;
        "onTrpBtnSubmited"?: (event: MyButtonCustomEvent<boolean>) => void;
        "target"?: string;
        "type"?: ButtonTypes;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "my-button": MyButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
