// Generated by CodiumAI

import { Pokemon } from '../types/pokemon';
import { getPokemonData } from './get-pokemon-data';

describe('testing function getPokemonData', () => {
  // Tests that the function getPokemonData returns an array of PokemonData objects
  it('should return an array of PokemonData objects', async () => {
    const pokemonData: Pokemon[] = await getPokemonData();
    expect(Array.isArray(pokemonData)).toBe(true);
    expect(pokemonData.length).toBe(12);
    expect(pokemonData[0]).toHaveProperty('id');
    expect(pokemonData[0]).toHaveProperty('name');
  });

  // Tests that the function correctly maps the id and name of each Pokemon
  it('maps id and name of each Pokemon correctly', async () => {
    const data: Pokemon[] = await getPokemonData();
    expect(data).toHaveLength(12);
    expect(data[0]).toHaveProperty('id');
    expect(data[0]).toHaveProperty('name');
  });
});
